version: '2'
services:
        nginx:
          build: nginx
          volumes:
            - ./nginx/www:/var/www/nginx
          networks:
            - se_backend
        grproxy:
          build: grproxy
          networks:
            - se_frontend
            - se_backend
        hbase:
          build: hbase
          networks:
            - se_backend
        gserve1:
          build: gserve
          networks:
            - se_backend
        gserve2:
          build: gserve
          networks:
            - se_backend

networks:
  se_backend:
    driver: bridge
  se_frontend:
    driver: bridge
