version: '2'
services:
        nginx:
          build: nginx
          volumes:
            - ./nginx/www:/var/www/nginx
          networks:
            - se_backend
          ports:
            - "80:80"
        grproxy:
          build: grproxy
          networks:
            - se_frontend
            - se_backend
        hbase:
          build: hbase
          networks:
            se_backend:
              aliases:
                - zookeeper
        gserve1:
          build: gserve
          environment:
            - ID=gserve1
          networks:
            - se_backend
          depends_on:
            - hbase
            - grproxy
        gserve2:
          build: gserve
          environment:
            - ID=gserve2
          networks:
            - se_backend
          depends_on:
            - hbase
            - grproxy
networks:
  se_backend:
    driver: bridge
  se_frontend:
    driver: bridge
